from typing import ContextManager, Any
from typing_extensions import TypeGuard
import pandas as pd

def obliterate_pandas() -> None: ...
def resurrect_pandas() -> None: ...
def missing_pandas() -> ContextManager[None]: ...
def is_pandas_available() -> bool: ...
def check_pandas() -> None: ...
def is_dataframe(value: Any) -> TypeGuard[pd.DataFrame]: ...

__all__ = [
    "pd",
    "obliterate_pandas",
    "resurrect_pandas",
    "is_pandas_available",
    "check_pandas",
    "is_dataframe",
]
