from typing import Iterable, Generator, Dict, Any, Tuple, overload
from typing_extensions import Literal

Attributes = Dict[Any, Any]

class NodeView:
    @overload
    def __call__(
        self, data: Literal[True]
    ) -> Generator[Tuple[Any, Attributes], None, None]: ...
    @overload
    def __call__(self) -> Generator[Any, None, None]: ...
    def __getitem__(self, key: Any) -> Attributes: ...
    def __iter__(self) -> Generator[Any, None, None]: ...

class EdgeView:
    @overload
    def __call__(
        self, data: Literal[True], keys: Literal[True]
    ) -> Generator[Tuple[Any, Any, Any, Attributes], None, None]: ...
    @overload
    def __call__(
        self, data: Literal[True]
    ) -> Generator[Tuple[Any, Attributes], None, None]: ...
    @overload
    def __call__(self) -> Generator[Any, None, None]: ...

class AbstractGraph:
    nodes: NodeView
    edges: EdgeView

    def __iter__(self) -> Generator[Any, None, None]: ...
    def order(self) -> int: ...
    def size(self) -> int: ...
    def add_node(self, key: Any, **kwargs: Any) -> None: ...
    def add_nodes_from(self, nbunch: Iterable[Any]) -> None: ...
    def add_edge(
        self, source: Any, target: Any, key: Any = ..., **kwargs: Any
    ) -> None: ...

class Graph(AbstractGraph): ...
class DiGraph(AbstractGraph): ...
class MultiGraph(AbstractGraph): ...
class MultiDiGraph(AbstractGraph): ...
